### ISSUE TITLE
Games cog causes high bot CPU load and lag

### ISSUE THREAD

**Issue by neonobjclash** [PaddoInWonderland/PaddoCogs#10]
One bot I run is in roughly 260 servers. It was always a CPU hog, but the lag recently started becoming unacceptable. After investigating, I narrowed down the cause of the bot's lag to the games cog.

When a member's status is changed, the cog validates, then reads the JSON of each server (ultimately parsing it twice if it already exists), then checks if the status has changed enough to qualify as significant. If it is, it computes the difference between the new game and *every single entry in the JSON*, which takes between linear and quadratic time for each comparison, and saves the JSON.

This algorithm performs well at eliminating duplicates, but is inefficient and scales in a manner that is unacceptable for large bots. I recommend the following:
* Only load the JSON if the change is significant (`match(before_game, after.game.name)`)
* Load the JSON once when the first significant change is detected in that server
  - keep it in RAM
* Only save the JSON on cog unload or if there hasn't been a change in status for a few seconds across the entire bot or per-server
   - This can be done using [`loop.call_later()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.call_later)
  - reschedule the call when a change is detected, but force a write after so many seconds
* Perform a check for an exact match before checking for the closest match
  - This is O(1) on hash tables, very fast
* Use Levenshtein distance to decide similarity instead of the Ratcliff-Obershelp algorithm

Only the last item above will change the behavior of the cog, the rest simply make it more efficient.

**Comment by PaddoInWonderland** [comment]
>One bot I run is in roughly 260 servers.

That's a lot, to be honest, and something I indeed did not anticipate. :)

> Only load the JSON if the change is significant (match(before_game, after.game.name))

Good idea. I have it now so that it only loads _and_ saves the JSON on a significant match.  In this instance it needs to load and save anyway, even if using `loop.call_later()`, it would only postpone the loading issue to a few moments later.

>Only save the JSON on cog unload or if there hasn't been a change in status for a few seconds across the entire bot or per-server

That wouldn't be very crash proof. Besides, the individual JSON files aren't that big (~300 KB for servers with ~5000 members) and shouldn't pose a problem once the solution above has been implemented.

I have updated the cog and would like you to test this.

**Comment by neonobjclash** [comment]
It's a little better, but still spikes heavily and lags noticably.

It looks like your code resets a game count to 1 if it's an exact match to `after.game.name.upper()`. This will almost never be true. Since the normal case is stored in the JSON, you should use the non-upper() string for comparison instead.

You don't need to `save_json()` when the dataset is empty or corrupt, since you save it at the end anyway.

Another idea is to ignore bots altogether, but I'm not sure how much that will save. It's probably best to filter out all of the song names etc. though.

On your matching: you aren't sorting to find the closest match, instead you're finding all of them and selecting the first one. If you want to exit on the first match then use a for loop and `break` out instead of evaluating the entire list. Otherwise, if you want to find the closest, you should use `sorted()`

>That wouldn't be very crash proof. Besides, the individual JSON files aren't that big (~300 KB for servers with ~5000 members) and shouldn't pose a problem once the solution above has been implemented.

Perhaps, but if a member is in multiple servers then the cog will load, check, and write all of them at once. That's what I was intending to avoid with the bot-wide delay idea. Besides, the data being collected here isn't very important. A few seconds lost here and there wouldn't matter.

**Comment by neonobjclash** [comment]
Even when it uses high CPU, the bot shouldn't lag. Perhaps the cause of the lag is the bot's worker thread pool becoming exhausted. This seems likely for users who share many servers with the bot.

**Comment by PaddoInWonderland** [comment]
>It's a little better, but still spikes heavily and lags noticably.

I have this issue as well right after updating. It doesn't happen when I restart the bot.

**Comment by PaddoInWonderland** [comment]
>It looks like your code resets a game count to 1 if it's an exact match to after.game.name.upper().

Oops. That was never the intention. Fixed.

>Another idea is to ignore bots altogether, but I'm not sure how much that will save.

It already ignores bots with `if not after.bot and after.game is not None:`

>Besides, the data being collected here isn't very important.

All data is important.

The cog now loads all existing JSON data once and I have changed the flow a bit.
