### ISSUE TITLE
statistics's problem

### ISSUE THREAD

**Issue by highlizard** [PaddoInWonderland/PaddoCogs#12]
I have pip3 install psutil --upgrade 
I use [P]stats my bot say this

`Error in command 'stats' - AttributeError: module 'discord' has no attribute 'Embed'`

**Comment by PaddoInWonderland** [comment]
Update your discord.py installation.

**Comment by Dax74** [comment]
I have an error with statistics.py with the last upgrade of Red (dd9fc4 - [Mod] Include trigger message in cleanup self for selfbots (#468)

Error logs:

`  File "/tux/Red-DiscordBot/cogs/statistics.py", line 134, in reload_stats
    msg = await self.retrieve_statistics()
  File "/tux/Red-DiscordBot/cogs/statistics.py", line 81, in retrieve_statistics
    uptime = abs(self.bot.uptime - int(time.perf_counter()))
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'int'`

**Comment by highlizard** [comment]
thank you I updated and it work
