### ISSUE TITLE
Away cog can be abused and spammed.

### ISSUE THREAD

**Issue by nikolaaa4** [PaddoInWonderland/PaddoCogs#13]
Basically the away cog responds when the channel is ignored by Red, and also it is spammable. https://swirlyhost.com/82be2985541b3355317a.png
Possibly make a option to ignore ignored channels or supply a character limit?

**Comment by PaddoInWonderland** [comment]
Any cog that replies back user content can be used for spamming. The cog is not responsible for users on your own server with your own bot.
