### ISSUE TITLE
statistics shows wrong uptime (timezone?)

### ISSUE THREAD

**Issue by fixator10** [PaddoInWonderland/PaddoCogs#19]
![2017-01-12 22-51-03](https://cloud.githubusercontent.com/assets/11073934/21904122/04a8bf2e-d91c-11e6-82ff-ac58b1f0b107.png)
So, 6H ≠ 2H.
Bot was running for 2 hours, but looks like it counts with difference in UTC (launch time is in UTC timezone?) and UTC+4 (my pc timezone)…

**Comment by PaddoInWonderland** [comment]
I have no idea what could cause this, the time the cog uses is from the bot itself (`self.bot.uptime`). That shows when the bot started. Both functions work the exact same way.

**Comment by fixator10** [comment]
But why then uptime show different time?

**Comment by PaddoInWonderland** [comment]
On my bot both are the correct time. Have you reloaded something 2 hours ago?

**Comment by fixator10** [comment]
Nope.
Restarted bot right now.
![image](https://cloud.githubusercontent.com/assets/11073934/21905525/268c03a8-d921-11e6-86a3-51f61ecb5acf.png)
It's has 4 hours of uptime from start.

**Comment by fixator10** [comment]
Updated, now it has 3 hours...
![image](https://cloud.githubusercontent.com/assets/11073934/21906276/0eeb0cc8-d924-11e6-88f0-e9a646bbfc92.png)

**Comment by fixator10** [comment]
I think i found way how to fix this out.
![image](https://cloud.githubusercontent.com/assets/11073934/21906309/3b6bb07c-d924-11e6-92ed-9a215c1e89c6.png)
Let me make an fork and then make an pull request

**Comment by fixator10** [comment]
Well, you did it by yourself, finally

**Comment by PaddoInWonderland** [comment]
¯\\\_(ツ)\_/¯
