### ISSUE TITLE
LogTools.py possible security flaw (due to discord's permissions hierarchy)

### ISSUE THREAD

**Issue by Yandols** [PaddoInWonderland/PaddoCogs#2]
Hey just wanna let you know after some testing, I found LogTools.py isn't as secure as it should be.

I was testing it out with one of my server members which has `manage_messages=True` permission only in a specific channel. Which means, said member should be only able to use the command to get the logs of that channel. However, he is also able to use command to get any logs of any channel, so as long as he is posting from that specific channel which he has `manage_messages=True` permissions to.

Which means, anyone with `manage_messages=True` in any channel can get logs from any other channel. Which raises a possible security flaw.

I myself have no idea how it can be fixed but I just wanted to let you know.
Yandols.

**Comment by PaddoInWonderland** [comment]
Thank you for bringing me this to light. I will fix it ASAP.

**Comment by PaddoInWonderland** [comment]
Issue solved, forgot to close.
