### ISSUE TITLE
Lastfm api will not work

### ISSUE THREAD

**Issue by DeathlyKnife** [PaddoInWonderland/PaddoCogs#20]
Last fm api key wil say its fake even when it is in use for more api i made.
it will set the api but wil give a error that the key is not valid even when it is working on my api.
my api i made with it is on http://api.gamemaster-army.com/thedeathlyknife/lastfm.php

**Comment by DeathlyKnife** [comment]
i have been loking into the sript and fixed it.
the url info that has been used for it was off with one caracter.

here you have the right script for it. 

[lastfm - update.txt](https://github.com/PaddoInWonderland/PaddoCogs/files/838929/lastfm.-.update.txt)

**Comment by PaddoInWonderland** [comment]
I recommend you doing a pull request.

**Comment by DeathlyKnife** [comment]
im new with github so idk how to do that.

**Comment by DeathlyKnife** [comment]
I have made one sorry if it is a little wrong but left a messge on the line where the error is.

**Comment by DeathlyKnife** [comment]
i installed the thing on a other bot and it is still giving a api error

**Comment by PaddoInWonderland** [comment]
Should be fixed now.
