### ISSUE TITLE
[seen] Seen does not properly handle spaces in names

### ISSUE THREAD

**Issue by HelmicNewciv** [PaddoInWonderland/PaddoCogs#29]
When using the !seen command using a user with a space in their name as an argument, the command doesn't work and instead returns instructions for use.  Using @ mentions works, but obviously that pings the user which is far from ideal.

The instructions are also missing the <p>, which implies the bot would respond if you type "seen @Helmic" just by itself.

**Comment by PaddoInWonderland** [comment]
That's not 'far from ideal' that's how it works. You either need to mention them, type their full user- or nickname or their user id. It returns instructions whenever it cannot find someone based on this input. I'm sorry, but that is not going to change due to how the API works.

**Comment by HelmicNewciv** [comment]
Huh?  I don't think I was clear the first time.

There is a user named Jim Sterling on my server.  I wish to use !seen Jim Sterling to see him.

Typing !seen Jim Sterling will not work.  !seen Jim Sterling#2446 also does not work. Only by using a mention does it work - it's far from ideal because it pings the user and bothers them every time someone wants to see when they last came online, which is obviously not a good thing when many people are trying to see when the last time an Internet personality was seen on the server.

Since the command doesn't take multiple arguments, it doesn't make sense for it to treat the spaces as adding multiple arguments.
