### ISSUE TITLE
Custom Role data dissapeared?

### ISSUE THREAD

**Issue by Savarien** [PaddoInWonderland/PaddoCogs#8]
So I had all these custom roles made and stuff.
They still exist but they aren't on the list of the roles anymore and because we also can't add roles to the list for some reason I have to do this process all over again :DDDDD

**Comment by PaddoInWonderland** [comment]
Does it give any error?

**Comment by Savarien** [comment]
Nah they just dissapeared from the customrole list

**Comment by JLBP** [comment]
Also having the same issue, there is nothing in the logs showing any errors but seems to happen when the connection to the discord server drops. I cant find anything in data relating to customroles either
